### ISSUE TITLE
Implement this on PHP server

### ISSUE THREAD

**Issue by Mostafa-shenawy** [JuanIrache/gopro-telemetry#123]
I'm running a WordPress website, I'd like to integrate this project on my website

As mentioned this project depend on Javascrit, but I got error while trying to implement this code via jQuery

require is not defined

Any help with this error and how can I implement this project through javascript or jQuery

const goproTelemetry = require('gopro-telemetry');
function callback(data) {
  // Do sometging with the data
}
const telemetry = goproTelemetry(input, options, callback);

What I'm trying to do is to upload video and then download metadata as CSV

**Comment by JuanIrache** [comment]
You will have to add require syntax support to your front end javascript. I don't know how to do that in Wordpress. You will have some additional problems, as for now this is not entirely compatible with browser JavaScript. You would have to get rid of the egm96 dependency. Ideally, you would run this on the server side instead of the browser, but if your server runs PHP and you are not able to run NodeJS, this will just not work. I hope this helps.

**Comment by Mostafa-shenawy** [comment]
Thank you for the explanation
