### ISSUE TITLE
 Number of frames in video

### ISSUE THREAD

**Issue by haimat** [JuanIrache/gopro-telemetry#169]
I am using `gopro-telemetry` with the `groupTimes: "frames"` option. Now when I count the occurences of `cts` in the result JSON file for my MP4 video I get 32457 frames. However, when I open the same video in Python and read the number of frames via OpenCV `vidcap.get(cv2.CAP_PROP_FRAME_COUNT)` this gives me 32460 - thus a small difference of 3 fewer frames in the JSON telemetry file.

The `cts` value of the first sample in the telemetry file is 0. Can I thus safely assume that these missing 3 samples belong to the last 3 frames in the video, for which we simply have no GPS data?

**Comment by JuanIrache** [comment]
Hi,

The metadata itself does not contain a clear way to match data samples with frames. The code makes some assuptions and guesses in order to match them. Results generally look good visually, but I do not have measured the error these assumptions produce. It's true that telemetry stops recording before the video ends, so telemetry is theoretically aligned to the beginning of the video, not the end, as you suspected. Other than that, for use cases where you need a very accurate match I would suggest running some tests yourself to measure the error or any necessary offsets.

**Comment by haimat** [comment]
Thanks for your feedback!
