### ISSUE TITLE
Documentation unclear

### ISSUE THREAD

**Issue by forna** [JuanIrache/gopro-telemetry#188]
Hi, this part of the documentation is not clear to me since the telemetry assignment does not follow the two possible usages -  as promise (with await) or with callback (with the callback argument).
Is there a working code example of how to reuse the parsedData?
```
const parsedData = goproTelemetry({ rawData, timing }, { raw: true });
const telemetry = goproTelemetry({ parsedData, timing });
```
Thanks

**Comment by JuanIrache** [comment]
I think the await is missing. It seems to be the case multiple times in the
README

**Comment by eortegaz** [comment]
Something else that isn't clear in the docs is how to merge raw for reuse (e.g. multiple presets for split footage). Assuming `raw` set to `true` will traverse the array, we still need to merge timing data to be passed as `{ parsedData, timing }` in the next stage.

The most sensible thing to do is that `raw` set to `true` should return the merged timing as `{ parsedData, timing }` since it will always be going through the next stage anyway. Or maybe adding a flag `returnTiming: true` for backwards compatibility.

For now I'll iterate raw and merge once parsed. I might write a function to keep `videoDuration` and `cts` running from the previous but it seems like a dirty fix. I'll try to figure something out and make a pull request 👍

**Comment by JuanIrache** [comment]
I haven't touched that part of the code in a long time, but I think the idea is you keep track of the timing on your end between calls. This is welcome as an option. Thanks.

I will close this as I just made the changes to the original issue.
